In [0]:
#import the libraries
import pandas as pd

In [0]:
#Read the data in csv file
npr=pd.read_csv('/content/npr.csv')

In [13]:
#Take a look at the head of the dataframe
npr.head(1)

Article
0  In the Washington of 2016, even when the polic...

In [14]:
#Let us take a look at the first Article
npr['Article'][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [15]:
#Check the lenght of dataset
#This is nothing but length of the dataframe
len(npr)
#So, there are 11992 Articles present in this dataset

11992

In [16]:
#Lets take alook at Article 4000
npr['Article'][4000]

'The headline shocked the   world of the surface Navy: Seven sailors aboard the destroyer USS Fitzgerald were killed, and other crew members injured, when the warship collided with a cargo vessel off Japan. As the Navy family grieves, both it and the wider world are asking the same question: How did this happen? The short answer is that no one knows  —   yet. Official inquiries into what led up to the encounter could take months or more. The Navy and the U. S. Coast Guard both likely will eventually issue reports that describe what happened and could make recommendations for preventing another such accident. ”I will not speculate on how long these investigations will last,” said Vice Adm. Joseph Aucoin, commander of the Navy’s 7th Fleet. The Fitzgerald and the other ships of Destroyer Squadron 15, based outside Tokyo, fall under his authority. There are clues, however, that explain how something like the Fitzgerald’s collision could happen, including photographs of the ships involved, 

In [0]:
#We do not know what topic these articles belong to
#We try to figure the topic for each of these Articles
#Before running LDA, we perform a little bit of preprocessing
#We perform Count Vectorization
from sklearn.feature_extraction.text import CountVectorizer

In [0]:
#Create an instance of Count Vectorizer
#We ignore certain terms for example common words.
#So, we specify maximum and minimum frequency for a term to be included in the document term matrix
#max_df gets rid of terms that are really common across the documents
#Value of max_df is between 0 and 1.
#PARAMETER 1:         max_df=0.9 is going to discard words that show up in 90 percent of documents
#PARAMETER 2:         min_df=  is the wrds that show up minimum amount of times
#You can actually pass the values to max_df and min_df as a ratio between 0 and 1
#You can also pass an integer,it will actually take into account as a raw number of documents
#If I pass min_df=2: this says that the minimum frequency for a word to be counted into the Count Vectorizer
#has to show up in atleast two documents
#Benefits achieved due to specifying max_df and min_df
#######This helps in throwing out some common words
#######This helps in throwing out some random words maybe typos and misspelling
#PARAMETER 3:         stop_words:    Specifies the language of stopwords
cv=CountVectorizer(max_df=0.9,min_df=2,stop_words='english')

In [0]:
#Other methods of performing above
#Tokenize the words
#Remove stopwords using Spacy

In [0]:
#There is no train test split involved as this is unseupervised
#We are fit transforming to the entire dataset: Creating the Document Term Matrix of the Article Column
dtm=cv.fit_transform(npr['Article'])


In [22]:
#Check the Document Term Matrix
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [0]:
#We have 54777 terms in the document term matrix
#Now perform LDA
from sklearn.decomposition import LatentDirichletAllocation

In [0]:
#There is no specific number for n_components
#It purely depends on domain experience and familiraty with the domain from where the dataset is from
#If we put n_components=7, taht means we want 7 topics to be returned
#If we want more details like... National Politics,State Politics under Politics topic
#You can increase the n_components
LDA=LatentDirichletAllocation(n_components=7,random_state=42)

In [25]:
#Fit LDA to document term matrix
LDA.fit(dtm)
#This will take time

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=7, n_jobs=None,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

In [27]:
#PART 1--------------------------#Grab the vocabulary of words
#Check the length of count vectorizer of document term matrix
len(cv.get_feature_names())

54777

In [28]:
#Check the type of above
type(cv.get_feature_names())

list

In [29]:
#Let us grab the word present at index number 50000
cv.get_feature_names()[50000]

'transcribe'

In [30]:
#Let us grab the word present at index number 41000
cv.get_feature_names()[41000]

'reproductive'

In [31]:
#Let us print some random words from the bunch of words
import random
#We are trying to grab some random word
random_word_id=random.randint(0,54777)
cv.get_feature_names()[random_word_id]

'leotard'

In [33]:
#PART 2--------------------------#Grab the topics
#Check the length of components
len(LDA.components_)

7

In [34]:
#Check the type of components
type(LDA.components_)
#It is an array containing probabilities for each word

numpy.ndarray

In [35]:
#Check the shape of array
LDA.components_.shape
#It is 7 topics by 54777 words

(7, 54777)

In [36]:
#Take a look at the ctual components
LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [0]:
#PART 3--------------------------#Grab the highest probability words per topic
#Let us take one topic
#We are considering the very first topic
#We still do not know what this topic actually represents
single_topic=LDA.components_[0]

In [0]:
#Example to explain argsort
import numpy as np

In [0]:
arr=np.array([10,200,1])

In [40]:
arr

array([ 10, 200,   1])

In [41]:
arr.argsort()
#The index positions are from lowest to highest
#Here index 2 value is 1 which is smallest
#Here index 0 value is 10
#Here index 1 value is 200 which is largest 

array([2, 0, 1])

In [42]:
#argsort returns index positions that would sort this array
single_topic.argsort()
#We are taking single topic and then figure out what index positions we should be looking at
#for high probability words for this particular single topic

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993])

In [43]:
#Now let us grab the top ten words for this topic
#ARGSORT----> returns index positions sorted from LEAST to GREATEST
#We are looking for TOP 10 values. SO we need the last ten values of argsort
#Below statement grabs the last ten values of .argsort
single_topic.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993])

In [0]:
#Let us try to indntify those top ten words with the help of indexes obtained in the above step
top_ten_words=single_topic.argsort()[-10:]

In [46]:
for index in top_ten_words:
  print(cv.get_feature_names()[index])

new
percent
government
company
million
care
people
health
said
says


In [0]:
#Now I want to take a look at top 20 words. This helps in understanding the topic more
top_twenty_words=single_topic.argsort()[-20:]

In [49]:
for index in top_twenty_words:
  print(cv.get_feature_names()[index])
#Looks like it is realted to some Health Insurance and policy

president
state
tax
insurance
trump
companies
money
year
federal
000
new
percent
government
company
million
care
people
health
said
says


In [53]:
#Let us create a loop that prints out top 15 words for each of the 7 topics
for i,topic in enumerate(LDA.components_):
  print(f"The top 15 words for the TOPIC #{i}")
  print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
  print('\n')
  print('\n')

The top 15 words for the TOPIC #0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']




The top 15 words for the TOPIC #1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']




The top 15 words for the TOPIC #2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']




The top 15 words for the TOPIC #3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']




The top 15 words for the TOPIC #4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']




The top 15 words for the TOPIC #5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 

In [54]:
#Attach these topic numbers to the original Articles
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [55]:
npr

Article
0      In the Washington of 2016, even when the polic...
1        Donald Trump has used Twitter  —   his prefe...
2        Donald Trump is unabashedly praising Russian...
3      Updated at 2:50 p. m. ET, Russian President Vl...
4      From photography, illustration and video, to d...
...                                                  ...
11987  The number of law enforcement officers shot an...
11988    Trump is busy these days with victory tours,...
11989  It’s always interesting for the Goats and Soda...
11990  The election of Donald Trump was a surprise to...
11991  Voters in the English city of Sunderland did s...

[11992 rows x 1 columns]

In [0]:
#Create new column to the npr dataframe that has the topic number
#Create a list of actual topics
topic_results=LDA.transform(dtm)

In [57]:
topic_results

array([[1.61040465e-02, 6.83341493e-01, 2.25376318e-04, ...,
        2.99652737e-01, 2.25479379e-04, 2.25497980e-04],
       [3.63424997e-02, 8.86130697e-01, 4.40751747e-04, ...,
        7.57636804e-02, 4.40866779e-04, 4.40835574e-04],
       [3.28569485e-04, 6.96344889e-01, 3.28302105e-04, ...,
        3.02012902e-01, 3.28724083e-04, 3.28352652e-04],
       ...,
       [1.44467964e-02, 1.60696622e-01, 1.73678310e-01, ...,
        2.24636569e-02, 3.98728349e-04, 3.98359730e-04],
       [4.33560738e-04, 3.53196803e-02, 4.33022554e-04, ...,
        9.62512640e-01, 4.33971991e-04, 4.33490254e-04],
       [3.98777533e-01, 2.54376049e-04, 3.59290659e-01, ...,
        2.40914375e-01, 2.54445555e-04, 2.54253739e-04]])

In [58]:
topic_results.shape

(11992, 7)

In [60]:
#Take a look at very first instance
topic_results[0]
#These are esentially the probabilities of belonging to a particular topic
#These are the probability of a document belonging to a particular topic
#The below 1.6104........... probability of document belonging to TOPIC0
#The below 6.8334........... probability of document belonging to TOPIC1

array([1.61040465e-02, 6.83341493e-01, 2.25376318e-04, 2.25369288e-04,
       2.99652737e-01, 2.25479379e-04, 2.25497980e-04])

In [61]:
#We can round of the above in case understanding the above is difficult
topic_results[0].round(2)
#The first Article at indexposition zero has the highest probability of 68% belonging to TOPIC 1

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [62]:
#Let us see what is the Article at index position zero
npr['Article'][0]
#This make sense that it has content realted to Political,Government,Russia,Military

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [63]:
#We are not interested in the probabilities
#we are interested in the index position of the highest probability
topic_results[0].argmax()

1

In [0]:
npr['Topic']=topic_results.argmax(axis=1)

In [65]:
npr

Article  Topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      2
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      1
11988    Trump is busy these days with victory tours,...      4
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      0

[11992 rows x 2 columns]