In [0]:
import numpy as np

In [0]:
#import inbuilt iris dataset
from sklearn.datasets import load_iris

In [0]:
iris=load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
#Print the description of the dataset
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [0]:

X=iris.data
#This is a numpy array with four columns

In [7]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [0]:
#The above four columns are 
####sepal length in cm
####sepal width in cm
####petal length in cm
####petal width in cm

In [0]:
#Let us create the target vazriable
y=iris.target

In [10]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [0]:
#The above represents class:
#####- Iris-Setosa
#####- Iris-Versicolour
#####- Iris-Virginica
#Now we perform one hot encoding on the y variable which is of categorical type
#class 0---->[1,0,0]
#class 1---->[0,1,0]
#class 2---->[0,0,1]

In [12]:
from keras.utils import to_categorical

Using TensorFlow backend.


In [0]:
y=to_categorical(y)

In [14]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [15]:
#Check the shape of y
y.shape

(150, 3)

In [0]:
#Create train test split
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33,random_state=42)

In [18]:
#Check y_test
y_test
#Everything will be shuffled

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

In [0]:
#In Neural Networks it is always better to scale or standardize the data
from sklearn.preprocessing import MinMaxScaler
#This fits all the values between a range
#It divides the values by the Max value so that everything falls between zero and one

In [20]:
#Let us see a demonstration on dividing by the Max value
np.array([5,10,15,20])/20

array([0.25, 0.5 , 0.75, 1.  ])

In [0]:
#Create object of MinMaxscaler
scaler_object=MinMaxScaler()

In [22]:
#We fit the MinMaxscaler object only to the training data
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [0]:
#We we create the scaled versions of our X Training Data
scaled_X_train=scaler_object.transform(X_train)

In [0]:
#We we create the scaled versions of our X Test Data
scaled_X_test=scaler_object.transform(X_test)

In [25]:
#Take a look at scaled training X data
scaled_X_train

array([[0.41176471, 0.40909091, 0.55357143, 0.5       ],
       [0.97058824, 0.45454545, 0.98214286, 0.83333333],
       [0.38235294, 0.45454545, 0.60714286, 0.58333333],
       [0.23529412, 0.68181818, 0.05357143, 0.04166667],
       [1.        , 0.36363636, 1.        , 0.79166667],
       [0.44117647, 0.31818182, 0.53571429, 0.375     ],
       [0.26470588, 0.63636364, 0.05357143, 0.04166667],
       [0.20588235, 0.68181818, 0.03571429, 0.08333333],
       [0.23529412, 0.81818182, 0.14285714, 0.125     ],
       [0.20588235, 0.        , 0.42857143, 0.375     ],
       [0.58823529, 0.31818182, 0.67857143, 0.70833333],
       [0.14705882, 0.63636364, 0.14285714, 0.04166667],
       [0.20588235, 0.45454545, 0.08928571, 0.04166667],
       [0.23529412, 0.59090909, 0.10714286, 0.16666667],
       [0.38235294, 0.31818182, 0.55357143, 0.5       ],
       [0.23529412, 0.63636364, 0.07142857, 0.04166667],
       [0.41176471, 0.45454545, 0.55357143, 0.45833333],
       [1.        , 0.81818182,

In [26]:
#Take a look at scaled test X data
scaled_X_test

array([[ 0.52941176,  0.36363636,  0.64285714,  0.45833333],
       [ 0.41176471,  0.81818182,  0.10714286,  0.08333333],
       [ 1.        ,  0.27272727,  1.03571429,  0.91666667],
       [ 0.5       ,  0.40909091,  0.60714286,  0.58333333],
       [ 0.73529412,  0.36363636,  0.66071429,  0.54166667],
       [ 0.32352941,  0.63636364,  0.07142857,  0.125     ],
       [ 0.38235294,  0.40909091,  0.44642857,  0.5       ],
       [ 0.76470588,  0.5       ,  0.71428571,  0.91666667],
       [ 0.55882353,  0.09090909,  0.60714286,  0.58333333],
       [ 0.44117647,  0.31818182,  0.5       ,  0.45833333],
       [ 0.64705882,  0.54545455,  0.71428571,  0.79166667],
       [ 0.14705882,  0.45454545,  0.05357143,  0.        ],
       [ 0.35294118,  0.68181818,  0.03571429,  0.04166667],
       [ 0.17647059,  0.5       ,  0.07142857,  0.        ],
       [ 0.23529412,  0.81818182,  0.07142857,  0.08333333],
       [ 0.58823529,  0.59090909,  0.64285714,  0.625     ],
       [ 0.64705882,  0.

In [0]:
#Build the Neural Network
#The below builds model with essentially sequence of layers
from keras.models import Sequential
from keras.layers import Dense

In [28]:
#We first cresate the Sequential Model and then try adding layers to it
model=Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
#units-refer to the number of neurons that go into this layer
#Here we are using 8. We are using double the number of features
#As of now we have no clue whether or not that number is correct or not
#Domain Knowledge is essential to get an idea on that number
#what should the activation function be
#input_dim=4 because we have four columns in the X
#Add another dense layer
model.add(Dense(8,input_dim=4,activation='relu'))

#Add the output layer
#We are going to have 3 neurons and that will have Soft Max activation
model.add(Dense(3,activation='softmax'))
#Each neuron is going to have probability for belonging to a particular class
#Which is why we perform onehot encoded
#At the end Neurons might return % as an output that represents chance for each index position
#The above will give an output something like this [0.2,0.3,0.5]
#Compile
#the loss selction depends on actually what we are performing
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [29]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [30]:
#Fit the above model to scaledX_train_data
#We don't need to scale y_train as they are already zeroes and ones
model.fit(scaled_X_train,y_train,epochs=150,verbose=2)
#one epoch is running thorigh the entire dataset
#Let us run for 150 epochs
#verbose is basically how much output you want information
#If verbose=0 you will not get anything reporting
#If verbose=1 it will show a progress bar
#If verbose=2 it will show how much loss, what is current accuracy

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/150





 - 0s - loss: 1.1356 - acc: 0.3100
Epoch 2/150
 - 0s - loss: 1.1284 - acc: 0.3100
Epoch 3/150
 - 0s - loss: 1.1217 - acc: 0.3100
Epoch 4/150
 - 0s - loss: 1.1164 - acc: 0.3100
Epoch 5/150
 - 0s - loss: 1.1103 - acc: 0.3100
Epoch 6/150
 - 0s - loss: 1.1064 - acc: 0.3100
Epoch 7/150
 - 0s - loss: 1.1005 - acc: 0.3400
Epoch 8/150
 - 0s - loss: 1.0958 - acc: 0.3700
Epoch 9/150
 - 0s - loss: 1.0911 - acc: 0.4100
Epoch 10/150
 - 0s - loss: 1.0872 - acc: 0.5100
Epoch 11/150
 - 0s - loss: 1.0828 - acc: 0.5900
Epoch 12/150
 - 0s - loss: 1.0794 - acc: 0.6100
Epoch 13/150
 - 0s - loss: 1.0762 - acc: 0.5900
Epoch 14/150
 - 0s - loss: 1.0723 - acc: 0.5900
Epoch 15/150
 - 0s - loss: 1.0688 - acc: 0.6100
Epoch 16/150
 - 0s - loss: 1.0653 - acc: 0.6200
Epoch 17/150
 - 0s - loss: 1.0615 - acc: 0.6200
Epoch 18/150
 - 0s - loss: 1.0578 - acc: 0.6200
Epoch 19/150
 - 0s - loss: 1.0539 - acc: 0.

##Keras Part Two

In [31]:
#Now we need to scale the test data(we already did this as scaled_X_test) or the new incoming data
#If you are giving a new value for testing that value should be scaled as our model is built for scaled values
#Let us check the predictions of the scaled_X_test data
model.predict(scaled_X_test)
#This will give the probabilities as output
#For example take the first row of output
#0.02931215, 0.5161774 , 0.45451042
#the probability of belonging to class zero  is 2.9%
#the probability of belonging to class one  is 51.6%
#the probability of belonging to class two  is 45.45%

array([[0.02931215, 0.5161774 , 0.45451042],
       [0.9239819 , 0.06552058, 0.01049744],
       [0.00150274, 0.2163753 , 0.782122  ],
       [0.03699883, 0.48744926, 0.4755519 ],
       [0.01278939, 0.4575539 , 0.5296567 ],
       [0.8907346 , 0.09538307, 0.01388235],
       [0.14644213, 0.5386306 , 0.3149273 ],
       [0.00577309, 0.33105257, 0.66317433],
       [0.02128422, 0.5244103 , 0.45430547],
       [0.07086972, 0.57925016, 0.3498801 ],
       [0.01357049, 0.35657257, 0.62985694],
       [0.89608365, 0.09336475, 0.01055158],
       [0.925289  , 0.06671976, 0.00799119],
       [0.89878523, 0.09041295, 0.01080174],
       [0.9588441 , 0.03556448, 0.00559133],
       [0.04405726, 0.43383726, 0.52210546],
       [0.00515486, 0.29160568, 0.70323944],
       [0.06336904, 0.60201734, 0.3346136 ],
       [0.04781337, 0.50911486, 0.4430718 ],
       [0.00607957, 0.32466698, 0.66925347],
       [0.91324306, 0.07610235, 0.01065463],
       [0.02034908, 0.40557173, 0.57407916],
       [0.

In [32]:
#Let us predict the classes of X_test data 
model.predict_classes(scaled_X_test)
#The output is not the one hot encoded values of the classes instead it prints the index position of the class
#We are now suppossed to pcompare these results with y_test

array([1, 0, 2, 1, 2, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0,
       0, 1, 2, 2, 1, 2])

In [33]:
 y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

In [0]:
#Compare results with predictions
predictions=model.predict_classes(scaled_X_test)

In [35]:
#We are going to transform our y_test
y_test.argmax(axis=1)
#This reprots back actual classes

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [0]:
 #Now the predictions and y_test are in the same format
 #Now we can compare
 from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [38]:
confusion_matrix(y_test.argmax(axis=1),predictions)

array([[19,  0,  0],
       [ 0, 10,  5],
       [ 0,  0, 16]])

In [39]:
#Print the classification report
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.67      0.80        15
           2       0.76      1.00      0.86        16

    accuracy                           0.90        50
   macro avg       0.92      0.89      0.89        50
weighted avg       0.92      0.90      0.90        50



In [40]:
#Accuracy Score
print(accuracy_score(y_test.argmax(axis=1),predictions))

0.9


In [0]:
#models related to text generation can take hours unlike the 150 epochs above
#We want to save and load our model
#We save the model as below
model.save('myfirstmodel.h5')
#h5 is the extension
#This saves all the weights of the network, so that we can quickly load it up again
#This will be useful when you shut down the computer and want to continue working next day

In [0]:
from keras.models import load_model

In [0]:
new_model=load_model('myfirstmodel.h5')

In [44]:
#Be careful with the naming scheme as we do not want to overwrite a particular model
#Now, I can use the new model similar to the old model
new_model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 2, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0,
       0, 1, 2, 2, 1, 2])